server:
  port: ${SERVER_PORT}

spring:
  application:
    name: chat-service
  cloud:
    compatibility-verifier:
      enabled: false
  profiles:
    include:
      - security
      - openapi
      - database
      - openfeign
      - kafka
      - rsocket