server:
  port: ${SERVER_PORT}

spring:
  application:
    name: chat-service
  cloud:
    compatibility-verifier:
      enabled: false
  profiles:
    include:
      - security
      - openapi
      - database
      - webclient
      - kafka
      - redis
      - crypto
      - firebase

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      access: read_only
